### ISSUE TITLE
Artist flags not showing

### ISSUE THREAD

**Issue by Helios-2429** [TT-ReBORN/Georgia-ReBORN#157]
Since upgrading to 3.0 RC1, artist flags have not shown in the metadata grid or the player lower bar. The issue persists in RC2.

Now I realize that I am not using the default artist country tag, but in past versions this required altering one line in the config file:
`"artist_country": "%country%", // Only used for displaying artist flags.`

I hope there's a solution, or maybe I'm just completely oblivious to an obvious fix on my end. But I miss my little flags :(

**Comment by TT-ReBORN** [comment]
Hi @Helios-2429,

I did not change anything related to the country flags since RC1.
The default tag is `"artist_country": "%artistcountry%",`

That means users need to tag their files with the %artistcountry% tag to successfully load them.
If you now change them to `"artist_country": "%country%",` you will need to use the %country% tag to be able to display them.

If there is no metadata ( no tag used ) available, how would the theme know what flag to load?
It has been always like this and there is no issue.

-TT

**Comment by TT-ReBORN** [comment]
P.S There was an issue with country flags but **ONLY** when using the Compact layout. This has been fixed in the latest master version. So if you are using the Compact layout, you would need to [download the master version from here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip) and replace your files.

**Comment by Helios-2429** [comment]
Changing %artistcountry% to %country% in the config file was a tip I picked up from some forum post years ago, from someone who like myself had a collection already tagged that way. It's worked for me for as long as I've been using GR.

That said, even if I turn back the change in the config file, and test with a file I've added an 'artistcountry' tag to for testing, it still does not display the flag.

**Comment by TT-ReBORN** [comment]
![flags](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/1539ed42-aa4b-43b3-ae92-5c39209f7088)
![flags2](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/58c9dae9-db0a-4d41-a8c4-93e4b256d3f0)

As you see it works as it should. Maybe you have deactivated displaying the country flags?
Check top menu `Options` > `Player controls` > `Lower bar` > `Show artist country flags`

If you want to display the artist country flags in the metadata grid in Details:
And top menu `Options` > `Details` > `Metadata grid` > `Show artist country flags`
With top menu `Options` > `Details` > `Metadata grid` > `Show artist`

Be sure that you have tagged your albums with the `%artistcountry%` or whatever tag you defined in your config.

-TT

**Comment by Helios-2429** [comment]
All of those are set as described, and I've double-checked that Help>Theme>Status>Flag images found is checked as well. I've also performed a fresh portable install of Foobar with a fresh install of GR, and tested with songs that have the country in the %artistcountry% tag.

Clearly something on my end is messing it up, I just wish I knew what it was...

**Comment by Helios-2429** [comment]
Just did another test install, this time on a different computer. Same procedure, same settings, flags everywhere. This just keeps getting more confusing.

**Comment by TT-ReBORN** [comment]
As I have mentioned before, there is an issue when using the RC-1/RC-2 versions **BUT ONLY** in the Compact layout 
( Options > Layout > Compact ), all other layouts ( Default, Artwork ) do work though. 
This issue was fixed in the [master version here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip), otherwise it should work just fine.

A possibility could be that you are using an old/bugged georgia-reborn-config.jsonc or your SMP panel properties are bugged. Before you do anything, first make a backup via top menu `Options` > `Settings` > `Theme backup` > `Make backup`.
After that delete your old `georgia-reborn-config.jsonc` file and clean your SMP panel properties ( while in `Playlist panel` -> `Shift + right click` > `Panel properties`... Then click on the `Clear` button and `OK` ).
Finally restore your backup via via top menu `Options` > `Settings` > `Theme backup` > `Restore backup`.

-TT

**Comment by TT-ReBORN** [comment]
@Helios-2429, I'm closing this now as there is no further activity...

**Comment by GhostwalkerGamma** [comment]
I'm having the same issue on windows 11 and latest foobar version, just update to newer version of georgia after a long time and flags no longer showing.
I tried everything mentioned above, include enabling the option to show country flags, update to the master version, uninstall / reinstall foobar and georgia,... but nothing seems to work.

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/100307581/e0cbdca3-c89c-410a-bda1-37360fd8eee4)

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/100307581/b2715011-3dff-4cfa-802b-309b7a38c70a)

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/100307581/256e1ba5-bbfe-4e70-b87f-68ef5737697c)

**Comment by TT-ReBORN** [comment]
Hi @GhostwalkerGamma,

this is really weird since I can not reproduce this issue and for most users it is working...

I do not know if this is a Windows 11 issue ( which I highly doubt ) or something in the latest version ( I checked the code and can not find any issues ). I'm using Windows 10 with the master version and there are no problems. 
It is possible that maybe there is a file path issue?
Are you using portable or standard foobar installation?

---

To further investigate this issue, can you do some tests?

Make two new portable foobar installs on your desktop with following directory names:
`foobar2000_new` and [install the latest master version from here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip).
`foobar2000_old` and [install the old v2.0.3b version from here](https://github.com/TT-ReBORN/Georgia-ReBORN/files/13685961/Georgia-ReBORN-v2.0.3b.zip).

When you start `foobar2000_old` the first time, you need to select `Columns UI` in the popup.

---

Both versions should display the artist country flags if the track has the `%ARTISTCOUNTRY%` tag with its value. 
But maybe there could be an issue in the latest version and you can verify with this test IF it is working properly.

Please report your findings, thanks!

-TT

**Comment by GhostwalkerGamma** [comment]
I'm using standard installation.

I tested with portable installation like you recomended, and country flags work fine in both version.

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/100307581/93052219-d569-4018-8bf3-b921721ce5d6)

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/100307581/6c26762c-4945-45e4-87ff-fdc8d2e152f5)

**Comment by Helios-2429** [comment]
For me, the issue occurs on Windows 10 and a portable installation, so I don't think it's a Windows 11 issue, at least...

**Comment by TT-ReBORN** [comment]
Ok guys,

there was an issue when the filepath had parentheses in the filename, e.g `foobar (test)`
I have fixed it in the latest commit and is available in the master.

This was a special case and there should be no other issues now.
I do not know if you guys had any parentheses or special chars in your filenames but another issue
could be that you had bugged ( invalid/old ) config settings in the Spider Monkey Panel properties settings 
or in your georgia-reborn-config.jsonc file.

Anyways all should be good now if you download the master version, thanks for reporting the issue!

-TT

**Comment by GhostwalkerGamma** [comment]
I tested the master version on standarad installation of foobar and country flags showed up properly now, cheers.

![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/100307581/b0051784-b09e-4726-b626-9ad549573020)

Thanks for quick response!
